In [1]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

from DataMacpy import *

DataMacpy Setup

In [2]:
# Veriyi içeri aktaralım.

# veri yolumuzu verelim
file_path = 'test_x.csv'

# verimizi okuyoruz. 
df = pd.read_csv(file_path)

print("Setup Complete")

Setup Complete

In [3]:
# Koşulları ve değerleri listeler halinde tanımlayalım
kosullar = [
    (df['Yaş Grubu'] == '18-30') | (df['Yaş Grubu'] == '31-40'),
    (df['Yaş Grubu'] == '41-50') | (df['Yaş Grubu'] == '51-60'),
    (df['Yaş Grubu'] == '>60')
]
degerler = [
    1,
    2,
    3
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yaş Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [4]:
# Koşulları ve değerleri listeler halinde tanımlayalım
kosullar = [
    (df['Eğitim Düzeyi'] == 'Eğitimsiz') | (df['Eğitim Düzeyi'] == 'İlkokul Mezunu') | (df['Eğitim Düzeyi'] == 'Ortaokul Mezunu'),
    (df['Eğitim Düzeyi'] == 'Lise Mezunu') | (df['Eğitim Düzeyi'] == 'Yüksekokul Mezunu'),
    (df['Eğitim Düzeyi'] == 'Üniversite Mezunu') | (df['Eğitim Düzeyi'] == 'Yüksek Lisans Mezunu'),
    (df['Eğitim Düzeyi'] == 'Doktora Mezunu') | (df['Eğitim Düzeyi'] == 'Doktora Ötesi')
]
degerler = [
    1,
    2,
    3,
    4
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Eğitim Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [5]:
kosullar = [
    (df['Yaşadığı Şehir'] == 'Köy veya Kasaba') | (df['Yaşadığı Şehir'] == 'Kırsal'),
    (df['Yaşadığı Şehir'] == 'Küçük Şehir') | (df['Yaşadığı Şehir'] == 'Büyük Şehir'),

]
degerler = [
    1,
    2
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yaşadığı Şehir Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [6]:
kosullar = [
    (df['Yıllık Ortalama Gelir'] <= 120000),
    (df['Yıllık Ortalama Gelir'] > 120000) & (df['Yıllık Ortalama Gelir'] <= 300000),
    (df['Yıllık Ortalama Gelir'] > 300000) & (df['Yıllık Ortalama Gelir'] <= 500000),
    (df['Yıllık Ortalama Gelir'] > 500000)
]
degerler = [
    1,
    2,
    3,
    4
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yıllık Ortalama Gelir Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [7]:
# Koşulları ve değerleri listeler halinde tanımlayalım
kosullar = [
    (df['Yıllık Ortalama Satın Alım Miktarı'] <= 8500),
    (df['Yıllık Ortalama Satın Alım Miktarı'] > 8500) & (df['Yıllık Ortalama Satın Alım Miktarı'] <= 20000),
    (df['Yıllık Ortalama Satın Alım Miktarı'] > 20000)
]
degerler = [
    1,
    2,
    3
    
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yıllık Ortalama Satın Alım Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [8]:
# Koşulları ve değerleri listeler halinde tanımlayalım
kosullar = [
    (df['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] <= 5),
    (df['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] > 5) & (df['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] <= 35),
    (df['Yıllık Ortalama Sipariş Verilen Ürün Adedi'] > 35)
]
degerler = [
    1,
    2,
    3
    
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yıllık Ortalama Sipariş Verilen Ürün Adedi Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [9]:
# Koşulları ve değerleri listeler halinde tanımlayalım
kosullar = [
    (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] <= 25),
    (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] > 25) & (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] <= 60),
    (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] > 60) & (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] <= 100),
    (df['Yıllık Ortalama Sepete Atılan Ürün Adedi'] > 100)
]
degerler = [
    1,
    2,
    3,
    4
]

# Dataframe'e Bölge adlı yeni bir kolon ekleyelim
df['Yıllık Ortalama Sepete Alınan Ürün Adedi Durumu'] = np.select(kosullar, degerler, default='Belirtilmedi')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2340 entries, 0 to 2339
Data columns (total 20 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   index                                              2340 non-null   int64
 1   Cinsiyet                                           2340 non-null   object
 2   Yaş Grubu                                          2340 non-null   object
 3   Medeni Durum                                       2340 non-null   object
 4   Eğitim Düzeyi                                      2340 non-null   object
 5   İstihdam Durumu                                    2340 non-null   object
 6   Yıllık Ortalama Gelir                              2340 non-null   float64
 7   Yaşadığı Şehir                                     2340 non-null   object
 8   En Çok İlgilendiği Ürün Grubu                      2340 non-null   object
 9   Yıllık Ortalama Satın Alım Miktarı                 2340 non-null   float64
 10  Yıllık Ortalama Sipariş Verilen Ürün Adedi         2340 non-null   float64
 11  Eğitime Devam Etme Durumu                          2340 non-null   object
 12  Yıllık Ortalama Sepete Atılan Ürün Adedi           2340 non-null   float64
 13  Yaş Durumu                                         2340 non-null   object
 14  Eğitim Durumu                                      2340 non-null   object
 15  Yaşadığı Şehir Durumu                              2340 non-null   object
 16  Yıllık Ortalama Gelir Durumu                       2340 non-null   object
 17  Yıllık Ortalama Satın Alım Durumu                  2340 non-null   object
 18  Yıllık Ortalama Sipariş Verilen Ürün Adedi Durumu  2340 non-null   object
 19  Yıllık Ortalama Sepete Alınan Ürün Adedi Durumu    2340 non-null   object
dtypes: float64(4), int64(1), object(15)
memory usage: 365.8+ KB

In [11]:
df

,index,Cinsiyet,Yaş Grubu,Medeni Durum,Eğitim Düzeyi,İstihdam Durumu,Yıllık Ortalama Gelir,Yaşadığı Şehir,En Çok İlgilendiği Ürün Grubu,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Eğitime Devam Etme Durumu,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Durumu,Eğitim Durumu,Yaşadığı Şehir Durumu,Yıllık Ortalama Gelir Durumu,Yıllık Ortalama Satın Alım Durumu,Yıllık Ortalama Sipariş Verilen Ürün Adedi Durumu,Yıllık Ortalama Sepete Alınan Ürün Adedi Durumu
0,0,Erkek,51-60,Evli,Yüksek Lisans Mezunu,Düzenli ve Ücretli Bir İşi Var,365331.930346,Köy veya Kasaba,Giyim,5566.587664,15.442635,Etmiyor,19.646460,2,3,1,3,1,2,1
1,1,Erkek,41-50,Bekar,Lise Mezunu,İşsiz veya Düzenli Bir İşi Yok,414899.236174,Büyük Şehir,Spor Malzemeleri,6756.766203,14.957246,Etmiyor,19.675863,2,2,2,3,1,2,1
2,2,Kadın,>60,Evli,Eğitimsiz,İşsiz veya Düzenli Bir İşi Yok,152825.872271,Küçük Şehir,Giyim,4493.915682,10.907930,Etmiyor,46.904518,3,1,2,2,1,2,2
3,3,Kadın,51-60,Evli,Doktora Ötesi,Düzenli ve Ücretli Bir İşi Var,489052.908472,Köy veya Kasaba,Kozmetik,42670.646595,32.333021,Etmiyor,48.083609,2,4,1,3,3,2,2
4,4,Erkek,18-30,Evli,Yüksek Lisans Mezunu,Kendi İşinin Sahibi,323635.711534,Küçük Şehir,Giyim,5959.266948,4.519968,Etmiyor,12.752491,1,3,2,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,2335,Kadın,18-30,Bekar,Yüksekokul Mezunu,Kendi İşinin Sahibi,259190.078834,Küçük Şehir,Ev ve Mobilya,9559.156534,41.883661,Ediyor,117.627785,1,2,2,2,2,3,4
2336,2336,Kadın,31-40,Evli,Lise Mezunu,İşsiz veya Düzenli Bir İşi Yok,194580.563177,Kırsal,Ev ve Mobilya,4070.232154,20.082996,Etmiyor,45.659622,1,2,1,2,1,2,2
2337,2337,Erkek,>60,Evli,Yüksek Lisans Mezunu,Düzenli ve Ücretli Bir İşi Var,357730.521969,Büyük Şehir,Ev ve Mobilya,22589.204381,18.922305,Etmiyor,100.691379,3,3,2,3,3,2,4
2338,2338,Erkek,18-30,Evli,Doktora Ötesi,Düzenli ve Ücretli Bir İşi Var,213179.637202,Küçük Şehir,Spor Malzemeleri,4205.390562,10.758108,Etmiyor,97.778913,1,4,2,2,1,2,3
2339,2339,Erkek,51-60,Evli,Üniversite Mezunu,Düzenli ve Ücretli Bir İşi Var,519013.573683,Köy veya Kasaba,Elektronik ve Teknolojik Ürünler,42675.353591,30.826534,Ediyor,39.657830,2,3,1,4,3,2,2

In [12]:
df.to_csv('test_x2.csv', index=False, encoding='utf-8')

In [14]:
# Veriyi içeri aktaralım.

# veri yolumuzu verelim
file_path = 'test_x2.csv'

# verimizi okuyoruz. 
df = pd.read_csv(file_path)

print("Setup Complete")
df

Setup Complete

,index,Cinsiyet,Yaş Grubu,Medeni Durum,Eğitim Düzeyi,İstihdam Durumu,Yıllık Ortalama Gelir,Yaşadığı Şehir,En Çok İlgilendiği Ürün Grubu,Yıllık Ortalama Satın Alım Miktarı,Yıllık Ortalama Sipariş Verilen Ürün Adedi,Eğitime Devam Etme Durumu,Yıllık Ortalama Sepete Atılan Ürün Adedi,Yaş Durumu,Eğitim Durumu,Yaşadığı Şehir Durumu,Yıllık Ortalama Gelir Durumu,Yıllık Ortalama Satın Alım Durumu,Yıllık Ortalama Sipariş Verilen Ürün Adedi Durumu,Yıllık Ortalama Sepete Alınan Ürün Adedi Durumu
0,0,Erkek,51-60,Evli,Yüksek Lisans Mezunu,Düzenli ve Ücretli Bir İşi Var,365331.930346,Köy veya Kasaba,Giyim,5566.587664,15.442635,Etmiyor,19.646460,2,3,1,3,1,2,1
1,1,Erkek,41-50,Bekar,Lise Mezunu,İşsiz veya Düzenli Bir İşi Yok,414899.236174,Büyük Şehir,Spor Malzemeleri,6756.766203,14.957246,Etmiyor,19.675863,2,2,2,3,1,2,1
2,2,Kadın,>60,Evli,Eğitimsiz,İşsiz veya Düzenli Bir İşi Yok,152825.872271,Küçük Şehir,Giyim,4493.915682,10.907930,Etmiyor,46.904518,3,1,2,2,1,2,2
3,3,Kadın,51-60,Evli,Doktora Ötesi,Düzenli ve Ücretli Bir İşi Var,489052.908472,Köy veya Kasaba,Kozmetik,42670.646595,32.333021,Etmiyor,48.083609,2,4,1,3,3,2,2
4,4,Erkek,18-30,Evli,Yüksek Lisans Mezunu,Kendi İşinin Sahibi,323635.711534,Küçük Şehir,Giyim,5959.266948,4.519968,Etmiyor,12.752491,1,3,2,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,2335,Kadın,18-30,Bekar,Yüksekokul Mezunu,Kendi İşinin Sahibi,259190.078834,Küçük Şehir,Ev ve Mobilya,9559.156534,41.883661,Ediyor,117.627785,1,2,2,2,2,3,4
2336,2336,Kadın,31-40,Evli,Lise Mezunu,İşsiz veya Düzenli Bir İşi Yok,194580.563177,Kırsal,Ev ve Mobilya,4070.232154,20.082996,Etmiyor,45.659622,1,2,1,2,1,2,2
2337,2337,Erkek,>60,Evli,Yüksek Lisans Mezunu,Düzenli ve Ücretli Bir İşi Var,357730.521969,Büyük Şehir,Ev ve Mobilya,22589.204381,18.922305,Etmiyor,100.691379,3,3,2,3,3,2,4
2338,2338,Erkek,18-30,Evli,Doktora Ötesi,Düzenli ve Ücretli Bir İşi Var,213179.637202,Küçük Şehir,Spor Malzemeleri,4205.390562,10.758108,Etmiyor,97.778913,1,4,2,2,1,2,3
2339,2339,Erkek,51-60,Evli,Üniversite Mezunu,Düzenli ve Ücretli Bir İşi Var,519013.573683,Köy veya Kasaba,Elektronik ve Teknolojik Ürünler,42675.353591,30.826534,Ediyor,39.657830,2,3,1,4,3,2,2